# coding: utf-8

"""
    OpenDota API

    # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 

    OpenAPI spec version: 18.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import od_python
from od_python.rest import ApiException
from od_python.apis.players_api import PlayersApi


class TestPlayersApi(unittest.TestCase):
    """ PlayersApi unit test stubs """

    def setUp(self):
        self.api = od_python.apis.players_api.PlayersApi()

    def tearDown(self):
        pass

    def test_players_account_id_counts_get(self):
        """
        Test case for players_account_id_counts_get

        GET /players/{account_id}/counts
        """
        pass

    def test_players_account_id_get(self):
        """
        Test case for players_account_id_get

        GET /players/{account_id}
        """
        pass

    def test_players_account_id_heroes_get(self):
        """
        Test case for players_account_id_heroes_get

        GET /players/{account_id}/heroes
        """
        pass

    def test_players_account_id_histograms_field_get(self):
        """
        Test case for players_account_id_histograms_field_get

        GET /players/{account_id}/histograms
        """
        pass

    def test_players_account_id_matches_get(self):
        """
        Test case for players_account_id_matches_get

        GET /players/{account_id}/matches
        """
        pass

    def test_players_account_id_peers_get(self):
        """
        Test case for players_account_id_peers_get

        GET /players/{account_id}/peers
        """
        pass

    def test_players_account_id_pros_get(self):
        """
        Test case for players_account_id_pros_get

        GET /players/{account_id}/pros
        """
        pass

    def test_players_account_id_rankings_get(self):
        """
        Test case for players_account_id_rankings_get

        GET /players/{account_id}/rankings
        """
        pass

    def test_players_account_id_ratings_get(self):
        """
        Test case for players_account_id_ratings_get

        GET /players/{account_id}/ratings
        """
        pass

    def test_players_account_id_recent_matches_get(self):
        """
        Test case for players_account_id_recent_matches_get

        GET /players/{account_id}/recentMatches
        """
        pass

    def test_players_account_id_refresh_post(self):
        """
        Test case for players_account_id_refresh_post

        POST /players/{account_id}/refresh
        """
        pass

    def test_players_account_id_totals_get(self):
        """
        Test case for players_account_id_totals_get

        GET /players/{account_id}/totals
        """
        pass

    def test_players_account_id_wardmap_get(self):
        """
        Test case for players_account_id_wardmap_get

        GET /players/{account_id}/wardmap
        """
        pass

    def test_players_account_id_wl_get(self):
        """
        Test case for players_account_id_wl_get

        GET /players/{account_id}/wl
        """
        pass

    def test_players_account_id_wordcloud_get(self):
        """
        Test case for players_account_id_wordcloud_get

        GET /players/{account_id}/wordcloud
        """
        pass


if __name__ == '__main__':
    unittest.main()
