# coding: utf-8

"""
    OpenDota API

    # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 

    OpenAPI spec version: 18.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import sys
import os
import re

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient


class HeroesApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client

    def heroes_get(self, **kwargs):
        """
        GET /heroes
        Get hero data

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.heroes_get(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :return: list[InlineResponse2003]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.heroes_get_with_http_info(**kwargs)
        else:
            (data) = self.heroes_get_with_http_info(**kwargs)
            return data

    def heroes_get_with_http_info(self, **kwargs):
        """
        GET /heroes
        Get hero data

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.heroes_get_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :return: list[InlineResponse2003]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []
        all_params.append('callback')
        all_params.append('_return_http_data_only')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heroes_get" % key
                )
            params[key] = val
        del params['kwargs']

        resource_path = '/heroes'.replace('{format}', 'json')
        path_params = {}

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type([])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'GET',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='list[InlineResponse2003]',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'),
                                            _return_http_data_only=params.get('_return_http_data_only'))

    def heroes_hero_id_durations_get(self, hero_id, **kwargs):
        """
        GET /heroes/{hero_id}/durations
        Get hero performance over a range of match durations

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.heroes_hero_id_durations_get(hero_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int hero_id: Hero ID (required)
        :return: list[InlineResponse2004]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.heroes_hero_id_durations_get_with_http_info(hero_id, **kwargs)
        else:
            (data) = self.heroes_hero_id_durations_get_with_http_info(hero_id, **kwargs)
            return data

    def heroes_hero_id_durations_get_with_http_info(self, hero_id, **kwargs):
        """
        GET /heroes/{hero_id}/durations
        Get hero performance over a range of match durations

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.heroes_hero_id_durations_get_with_http_info(hero_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int hero_id: Hero ID (required)
        :return: list[InlineResponse2004]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['hero_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heroes_hero_id_durations_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'hero_id' is set
        if ('hero_id' not in params) or (params['hero_id'] is None):
            raise ValueError("Missing the required parameter `hero_id` when calling `heroes_hero_id_durations_get`")

        resource_path = '/heroes/{hero_id}/durations'.replace('{format}', 'json')
        path_params = {}
        if 'hero_id' in params:
            path_params['hero_id'] = params['hero_id']

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type([])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'GET',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='list[InlineResponse2004]',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'),
                                            _return_http_data_only=params.get('_return_http_data_only'))

    def heroes_hero_id_item_popularity_get(self, hero_id, **kwargs):
        """
        GET /heroes/{hero_id}/itemPopularity
        Get item popularity of hero categoried by start, early, mid and late game, analyzed from professional games

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.heroes_hero_id_item_popularity_get(hero_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int hero_id: Hero ID (required)
        :return: InlineResponse2005
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.heroes_hero_id_item_popularity_get_with_http_info(hero_id, **kwargs)
        else:
            (data) = self.heroes_hero_id_item_popularity_get_with_http_info(hero_id, **kwargs)
            return data

    def heroes_hero_id_item_popularity_get_with_http_info(self, hero_id, **kwargs):
        """
        GET /heroes/{hero_id}/itemPopularity
        Get item popularity of hero categoried by start, early, mid and late game, analyzed from professional games

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.heroes_hero_id_item_popularity_get_with_http_info(hero_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int hero_id: Hero ID (required)
        :return: InlineResponse2005
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['hero_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heroes_hero_id_item_popularity_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'hero_id' is set
        if ('hero_id' not in params) or (params['hero_id'] is None):
            raise ValueError("Missing the required parameter `hero_id` when calling `heroes_hero_id_item_popularity_get`")

        resource_path = '/heroes/{hero_id}/itemPopularity'.replace('{format}', 'json')
        path_params = {}
        if 'hero_id' in params:
            path_params['hero_id'] = params['hero_id']

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type([])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'GET',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='InlineResponse2005',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'),
                                            _return_http_data_only=params.get('_return_http_data_only'))

    def heroes_hero_id_matches_get(self, hero_id, **kwargs):
        """
        GET /heroes/{hero_id}/matches
        Get recent matches with a hero

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.heroes_hero_id_matches_get(hero_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int hero_id: Hero ID (required)
        :return: list[InlineResponse2006]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.heroes_hero_id_matches_get_with_http_info(hero_id, **kwargs)
        else:
            (data) = self.heroes_hero_id_matches_get_with_http_info(hero_id, **kwargs)
            return data

    def heroes_hero_id_matches_get_with_http_info(self, hero_id, **kwargs):
        """
        GET /heroes/{hero_id}/matches
        Get recent matches with a hero

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.heroes_hero_id_matches_get_with_http_info(hero_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int hero_id: Hero ID (required)
        :return: list[InlineResponse2006]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['hero_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heroes_hero_id_matches_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'hero_id' is set
        if ('hero_id' not in params) or (params['hero_id'] is None):
            raise ValueError("Missing the required parameter `hero_id` when calling `heroes_hero_id_matches_get`")

        resource_path = '/heroes/{hero_id}/matches'.replace('{format}', 'json')
        path_params = {}
        if 'hero_id' in params:
            path_params['hero_id'] = params['hero_id']

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type([])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'GET',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='list[InlineResponse2006]',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'),
                                            _return_http_data_only=params.get('_return_http_data_only'))

    def heroes_hero_id_matchups_get(self, hero_id, **kwargs):
        """
        GET /heroes/{hero_id}/matchups
        Get results against other heroes for a hero

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.heroes_hero_id_matchups_get(hero_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int hero_id: Hero ID (required)
        :return: list[InlineResponse2007]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.heroes_hero_id_matchups_get_with_http_info(hero_id, **kwargs)
        else:
            (data) = self.heroes_hero_id_matchups_get_with_http_info(hero_id, **kwargs)
            return data

    def heroes_hero_id_matchups_get_with_http_info(self, hero_id, **kwargs):
        """
        GET /heroes/{hero_id}/matchups
        Get results against other heroes for a hero

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.heroes_hero_id_matchups_get_with_http_info(hero_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int hero_id: Hero ID (required)
        :return: list[InlineResponse2007]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['hero_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heroes_hero_id_matchups_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'hero_id' is set
        if ('hero_id' not in params) or (params['hero_id'] is None):
            raise ValueError("Missing the required parameter `hero_id` when calling `heroes_hero_id_matchups_get`")

        resource_path = '/heroes/{hero_id}/matchups'.replace('{format}', 'json')
        path_params = {}
        if 'hero_id' in params:
            path_params['hero_id'] = params['hero_id']

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type([])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'GET',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='list[InlineResponse2007]',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'),
                                            _return_http_data_only=params.get('_return_http_data_only'))

    def heroes_hero_id_players_get(self, hero_id, **kwargs):
        """
        GET /heroes/{hero_id}/players
        Get players who have played this hero

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.heroes_hero_id_players_get(hero_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int hero_id: Hero ID (required)
        :return: list[list[object]]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.heroes_hero_id_players_get_with_http_info(hero_id, **kwargs)
        else:
            (data) = self.heroes_hero_id_players_get_with_http_info(hero_id, **kwargs)
            return data

    def heroes_hero_id_players_get_with_http_info(self, hero_id, **kwargs):
        """
        GET /heroes/{hero_id}/players
        Get players who have played this hero

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.heroes_hero_id_players_get_with_http_info(hero_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int hero_id: Hero ID (required)
        :return: list[list[object]]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['hero_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heroes_hero_id_players_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'hero_id' is set
        if ('hero_id' not in params) or (params['hero_id'] is None):
            raise ValueError("Missing the required parameter `hero_id` when calling `heroes_hero_id_players_get`")

        resource_path = '/heroes/{hero_id}/players'.replace('{format}', 'json')
        path_params = {}
        if 'hero_id' in params:
            path_params['hero_id'] = params['hero_id']

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type([])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'GET',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='list[list[object]]',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'),
                                            _return_http_data_only=params.get('_return_http_data_only'))
