# coding: utf-8

"""
    OpenDota API

    # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 

    OpenAPI spec version: 18.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class InlineResponse2005(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, start_game_items=None, early_game_items=None, mid_game_items=None, late_game_items=None):
        """
        InlineResponse2005 - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'start_game_items': 'InlineResponse2005StartGameItems',
            'early_game_items': 'InlineResponse2005EarlyGameItems',
            'mid_game_items': 'InlineResponse2005MidGameItems',
            'late_game_items': 'InlineResponse2005LateGameItems'
        }

        self.attribute_map = {
            'start_game_items': 'start_game_items',
            'early_game_items': 'early_game_items',
            'mid_game_items': 'mid_game_items',
            'late_game_items': 'late_game_items'
        }

        self._start_game_items = start_game_items
        self._early_game_items = early_game_items
        self._mid_game_items = mid_game_items
        self._late_game_items = late_game_items

    @property
    def start_game_items(self):
        """
        Gets the start_game_items of this InlineResponse2005.


        :return: The start_game_items of this InlineResponse2005.
        :rtype: InlineResponse2005StartGameItems
        """
        return self._start_game_items

    @start_game_items.setter
    def start_game_items(self, start_game_items):
        """
        Sets the start_game_items of this InlineResponse2005.


        :param start_game_items: The start_game_items of this InlineResponse2005.
        :type: InlineResponse2005StartGameItems
        """

        self._start_game_items = start_game_items

    @property
    def early_game_items(self):
        """
        Gets the early_game_items of this InlineResponse2005.


        :return: The early_game_items of this InlineResponse2005.
        :rtype: InlineResponse2005EarlyGameItems
        """
        return self._early_game_items

    @early_game_items.setter
    def early_game_items(self, early_game_items):
        """
        Sets the early_game_items of this InlineResponse2005.


        :param early_game_items: The early_game_items of this InlineResponse2005.
        :type: InlineResponse2005EarlyGameItems
        """

        self._early_game_items = early_game_items

    @property
    def mid_game_items(self):
        """
        Gets the mid_game_items of this InlineResponse2005.


        :return: The mid_game_items of this InlineResponse2005.
        :rtype: InlineResponse2005MidGameItems
        """
        return self._mid_game_items

    @mid_game_items.setter
    def mid_game_items(self, mid_game_items):
        """
        Sets the mid_game_items of this InlineResponse2005.


        :param mid_game_items: The mid_game_items of this InlineResponse2005.
        :type: InlineResponse2005MidGameItems
        """

        self._mid_game_items = mid_game_items

    @property
    def late_game_items(self):
        """
        Gets the late_game_items of this InlineResponse2005.


        :return: The late_game_items of this InlineResponse2005.
        :rtype: InlineResponse2005LateGameItems
        """
        return self._late_game_items

    @late_game_items.setter
    def late_game_items(self, late_game_items):
        """
        Sets the late_game_items of this InlineResponse2005.


        :param late_game_items: The late_game_items of this InlineResponse2005.
        :type: InlineResponse2005LateGameItems
        """

        self._late_game_items = late_game_items

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
