# coding: utf-8

"""
    OpenDota API

    # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 

    OpenAPI spec version: 18.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class InlineResponse2009Chat(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, time=None, unit=None, key=None, slot=None, player_slot=None):
        """
        InlineResponse2009Chat - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'time': 'int',
            'unit': 'str',
            'key': 'str',
            'slot': 'int',
            'player_slot': 'int'
        }

        self.attribute_map = {
            'time': 'time',
            'unit': 'unit',
            'key': 'key',
            'slot': 'slot',
            'player_slot': 'player_slot'
        }

        self._time = time
        self._unit = unit
        self._key = key
        self._slot = slot
        self._player_slot = player_slot

    @property
    def time(self):
        """
        Gets the time of this InlineResponse2009Chat.
        Time in seconds at which the message was said

        :return: The time of this InlineResponse2009Chat.
        :rtype: int
        """
        return self._time

    @time.setter
    def time(self, time):
        """
        Sets the time of this InlineResponse2009Chat.
        Time in seconds at which the message was said

        :param time: The time of this InlineResponse2009Chat.
        :type: int
        """

        self._time = time

    @property
    def unit(self):
        """
        Gets the unit of this InlineResponse2009Chat.
        Name of the player who sent the message

        :return: The unit of this InlineResponse2009Chat.
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit):
        """
        Sets the unit of this InlineResponse2009Chat.
        Name of the player who sent the message

        :param unit: The unit of this InlineResponse2009Chat.
        :type: str
        """

        self._unit = unit

    @property
    def key(self):
        """
        Gets the key of this InlineResponse2009Chat.
        The message the player sent

        :return: The key of this InlineResponse2009Chat.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """
        Sets the key of this InlineResponse2009Chat.
        The message the player sent

        :param key: The key of this InlineResponse2009Chat.
        :type: str
        """

        self._key = key

    @property
    def slot(self):
        """
        Gets the slot of this InlineResponse2009Chat.
        slot

        :return: The slot of this InlineResponse2009Chat.
        :rtype: int
        """
        return self._slot

    @slot.setter
    def slot(self, slot):
        """
        Sets the slot of this InlineResponse2009Chat.
        slot

        :param slot: The slot of this InlineResponse2009Chat.
        :type: int
        """

        self._slot = slot

    @property
    def player_slot(self):
        """
        Gets the player_slot of this InlineResponse2009Chat.
        Which slot the player is in. 0-127 are Radiant, 128-255 are Dire

        :return: The player_slot of this InlineResponse2009Chat.
        :rtype: int
        """
        return self._player_slot

    @player_slot.setter
    def player_slot(self, player_slot):
        """
        Sets the player_slot of this InlineResponse2009Chat.
        Which slot the player is in. 0-127 are Radiant, 128-255 are Dire

        :param player_slot: The player_slot of this InlineResponse2009Chat.
        :type: int
        """

        self._player_slot = player_slot

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
