# coding: utf-8

"""
    OpenDota API

    # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 

    OpenAPI spec version: 18.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class InlineResponse2001CountryMmrRows(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, loccountrycode=None, count=None, avg=None, common=None):
        """
        InlineResponse2001CountryMmrRows - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'loccountrycode': 'str',
            'count': 'int',
            'avg': 'str',
            'common': 'str'
        }

        self.attribute_map = {
            'loccountrycode': 'loccountrycode',
            'count': 'count',
            'avg': 'avg',
            'common': 'common'
        }

        self._loccountrycode = loccountrycode
        self._count = count
        self._avg = avg
        self._common = common

    @property
    def loccountrycode(self):
        """
        Gets the loccountrycode of this InlineResponse2001CountryMmrRows.
        loccountrycode

        :return: The loccountrycode of this InlineResponse2001CountryMmrRows.
        :rtype: str
        """
        return self._loccountrycode

    @loccountrycode.setter
    def loccountrycode(self, loccountrycode):
        """
        Sets the loccountrycode of this InlineResponse2001CountryMmrRows.
        loccountrycode

        :param loccountrycode: The loccountrycode of this InlineResponse2001CountryMmrRows.
        :type: str
        """

        self._loccountrycode = loccountrycode

    @property
    def count(self):
        """
        Gets the count of this InlineResponse2001CountryMmrRows.
        count

        :return: The count of this InlineResponse2001CountryMmrRows.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """
        Sets the count of this InlineResponse2001CountryMmrRows.
        count

        :param count: The count of this InlineResponse2001CountryMmrRows.
        :type: int
        """

        self._count = count

    @property
    def avg(self):
        """
        Gets the avg of this InlineResponse2001CountryMmrRows.
        avg

        :return: The avg of this InlineResponse2001CountryMmrRows.
        :rtype: str
        """
        return self._avg

    @avg.setter
    def avg(self, avg):
        """
        Sets the avg of this InlineResponse2001CountryMmrRows.
        avg

        :param avg: The avg of this InlineResponse2001CountryMmrRows.
        :type: str
        """

        self._avg = avg

    @property
    def common(self):
        """
        Gets the common of this InlineResponse2001CountryMmrRows.
        common

        :return: The common of this InlineResponse2001CountryMmrRows.
        :rtype: str
        """
        return self._common

    @common.setter
    def common(self, common):
        """
        Sets the common of this InlineResponse2001CountryMmrRows.
        common

        :param common: The common of this InlineResponse2001CountryMmrRows.
        :type: str
        """

        self._common = common

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
