# coding: utf-8

"""
    OpenDota API

    # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 

    OpenAPI spec version: 18.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class InlineResponse2001(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, ranks=None, mmr=None, country_mmr=None):
        """
        InlineResponse2001 - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'ranks': 'InlineResponse2001Ranks',
            'mmr': 'InlineResponse2001Mmr',
            'country_mmr': 'InlineResponse2001CountryMmr'
        }

        self.attribute_map = {
            'ranks': 'ranks',
            'mmr': 'mmr',
            'country_mmr': 'country_mmr'
        }

        self._ranks = ranks
        self._mmr = mmr
        self._country_mmr = country_mmr

    @property
    def ranks(self):
        """
        Gets the ranks of this InlineResponse2001.


        :return: The ranks of this InlineResponse2001.
        :rtype: InlineResponse2001Ranks
        """
        return self._ranks

    @ranks.setter
    def ranks(self, ranks):
        """
        Sets the ranks of this InlineResponse2001.


        :param ranks: The ranks of this InlineResponse2001.
        :type: InlineResponse2001Ranks
        """

        self._ranks = ranks

    @property
    def mmr(self):
        """
        Gets the mmr of this InlineResponse2001.


        :return: The mmr of this InlineResponse2001.
        :rtype: InlineResponse2001Mmr
        """
        return self._mmr

    @mmr.setter
    def mmr(self, mmr):
        """
        Sets the mmr of this InlineResponse2001.


        :param mmr: The mmr of this InlineResponse2001.
        :type: InlineResponse2001Mmr
        """

        self._mmr = mmr

    @property
    def country_mmr(self):
        """
        Gets the country_mmr of this InlineResponse2001.


        :return: The country_mmr of this InlineResponse2001.
        :rtype: InlineResponse2001CountryMmr
        """
        return self._country_mmr

    @country_mmr.setter
    def country_mmr(self, country_mmr):
        """
        Sets the country_mmr of this InlineResponse2001.


        :param country_mmr: The country_mmr of this InlineResponse2001.
        :type: InlineResponse2001CountryMmr
        """

        self._country_mmr = country_mmr

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
