# coding: utf-8

"""
    OpenDota API

    # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 

    OpenAPI spec version: 18.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class InlineResponse2008(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, leagueid=None, ticket=None, banner=None, tier=None, name=None):
        """
        InlineResponse2008 - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'leagueid': 'int',
            'ticket': 'str',
            'banner': 'str',
            'tier': 'str',
            'name': 'str'
        }

        self.attribute_map = {
            'leagueid': 'leagueid',
            'ticket': 'ticket',
            'banner': 'banner',
            'tier': 'tier',
            'name': 'name'
        }

        self._leagueid = leagueid
        self._ticket = ticket
        self._banner = banner
        self._tier = tier
        self._name = name

    @property
    def leagueid(self):
        """
        Gets the leagueid of this InlineResponse2008.
        leagueid

        :return: The leagueid of this InlineResponse2008.
        :rtype: int
        """
        return self._leagueid

    @leagueid.setter
    def leagueid(self, leagueid):
        """
        Sets the leagueid of this InlineResponse2008.
        leagueid

        :param leagueid: The leagueid of this InlineResponse2008.
        :type: int
        """

        self._leagueid = leagueid

    @property
    def ticket(self):
        """
        Gets the ticket of this InlineResponse2008.
        ticket

        :return: The ticket of this InlineResponse2008.
        :rtype: str
        """
        return self._ticket

    @ticket.setter
    def ticket(self, ticket):
        """
        Sets the ticket of this InlineResponse2008.
        ticket

        :param ticket: The ticket of this InlineResponse2008.
        :type: str
        """

        self._ticket = ticket

    @property
    def banner(self):
        """
        Gets the banner of this InlineResponse2008.
        banner

        :return: The banner of this InlineResponse2008.
        :rtype: str
        """
        return self._banner

    @banner.setter
    def banner(self, banner):
        """
        Sets the banner of this InlineResponse2008.
        banner

        :param banner: The banner of this InlineResponse2008.
        :type: str
        """

        self._banner = banner

    @property
    def tier(self):
        """
        Gets the tier of this InlineResponse2008.
        tier

        :return: The tier of this InlineResponse2008.
        :rtype: str
        """
        return self._tier

    @tier.setter
    def tier(self, tier):
        """
        Sets the tier of this InlineResponse2008.
        tier

        :param tier: The tier of this InlineResponse2008.
        :type: str
        """

        self._tier = tier

    @property
    def name(self):
        """
        Gets the name of this InlineResponse2008.
        name

        :return: The name of this InlineResponse2008.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this InlineResponse2008.
        name

        :param name: The name of this InlineResponse2008.
        :type: str
        """

        self._name = name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
