# coding: utf-8

"""
    OpenDota API

    # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 

    OpenAPI spec version: 18.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class InlineResponse2001RanksRows(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, bin=None, bin_name=None, count=None, cumulative_sum=None):
        """
        InlineResponse2001RanksRows - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'bin': 'int',
            'bin_name': 'int',
            'count': 'int',
            'cumulative_sum': 'int'
        }

        self.attribute_map = {
            'bin': 'bin',
            'bin_name': 'bin_name',
            'count': 'count',
            'cumulative_sum': 'cumulative_sum'
        }

        self._bin = bin
        self._bin_name = bin_name
        self._count = count
        self._cumulative_sum = cumulative_sum

    @property
    def bin(self):
        """
        Gets the bin of this InlineResponse2001RanksRows.
        bin

        :return: The bin of this InlineResponse2001RanksRows.
        :rtype: int
        """
        return self._bin

    @bin.setter
    def bin(self, bin):
        """
        Sets the bin of this InlineResponse2001RanksRows.
        bin

        :param bin: The bin of this InlineResponse2001RanksRows.
        :type: int
        """

        self._bin = bin

    @property
    def bin_name(self):
        """
        Gets the bin_name of this InlineResponse2001RanksRows.
        bin_name

        :return: The bin_name of this InlineResponse2001RanksRows.
        :rtype: int
        """
        return self._bin_name

    @bin_name.setter
    def bin_name(self, bin_name):
        """
        Sets the bin_name of this InlineResponse2001RanksRows.
        bin_name

        :param bin_name: The bin_name of this InlineResponse2001RanksRows.
        :type: int
        """

        self._bin_name = bin_name

    @property
    def count(self):
        """
        Gets the count of this InlineResponse2001RanksRows.
        count

        :return: The count of this InlineResponse2001RanksRows.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """
        Sets the count of this InlineResponse2001RanksRows.
        count

        :param count: The count of this InlineResponse2001RanksRows.
        :type: int
        """

        self._count = count

    @property
    def cumulative_sum(self):
        """
        Gets the cumulative_sum of this InlineResponse2001RanksRows.
        cumulative_sum

        :return: The cumulative_sum of this InlineResponse2001RanksRows.
        :rtype: int
        """
        return self._cumulative_sum

    @cumulative_sum.setter
    def cumulative_sum(self, cumulative_sum):
        """
        Sets the cumulative_sum of this InlineResponse2001RanksRows.
        cumulative_sum

        :param cumulative_sum: The cumulative_sum of this InlineResponse2001RanksRows.
        :type: int
        """

        self._cumulative_sum = cumulative_sum

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
