# coding: utf-8

"""
    OpenDota API

    # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 

    OpenAPI spec version: 18.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class InlineResponse20012MmrEstimate(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, estimate=None, std_dev=None, n=None):
        """
        InlineResponse20012MmrEstimate - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'estimate': 'float',
            'std_dev': 'float',
            'n': 'int'
        }

        self.attribute_map = {
            'estimate': 'estimate',
            'std_dev': 'stdDev',
            'n': 'n'
        }

        self._estimate = estimate
        self._std_dev = std_dev
        self._n = n

    @property
    def estimate(self):
        """
        Gets the estimate of this InlineResponse20012MmrEstimate.
        estimate

        :return: The estimate of this InlineResponse20012MmrEstimate.
        :rtype: float
        """
        return self._estimate

    @estimate.setter
    def estimate(self, estimate):
        """
        Sets the estimate of this InlineResponse20012MmrEstimate.
        estimate

        :param estimate: The estimate of this InlineResponse20012MmrEstimate.
        :type: float
        """

        self._estimate = estimate

    @property
    def std_dev(self):
        """
        Gets the std_dev of this InlineResponse20012MmrEstimate.
        stdDev

        :return: The std_dev of this InlineResponse20012MmrEstimate.
        :rtype: float
        """
        return self._std_dev

    @std_dev.setter
    def std_dev(self, std_dev):
        """
        Sets the std_dev of this InlineResponse20012MmrEstimate.
        stdDev

        :param std_dev: The std_dev of this InlineResponse20012MmrEstimate.
        :type: float
        """

        self._std_dev = std_dev

    @property
    def n(self):
        """
        Gets the n of this InlineResponse20012MmrEstimate.
        n

        :return: The n of this InlineResponse20012MmrEstimate.
        :rtype: int
        """
        return self._n

    @n.setter
    def n(self, n):
        """
        Sets the n of this InlineResponse20012MmrEstimate.
        n

        :param n: The n of this InlineResponse20012MmrEstimate.
        :type: int
        """

        self._n = n

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
