# coding: utf-8

"""
    OpenDota API

    # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 

    OpenAPI spec version: 18.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class InlineResponse20027Rankings(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, account_id=None, score=None, steamid=None, avatar=None, avatarmedium=None, avatarfull=None, profileurl=None, personaname=None, cheese=None, fh_unavailable=None, loccountrycode=None, rank_tier=None):
        """
        InlineResponse20027Rankings - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'account_id': 'int',
            'score': 'str',
            'steamid': 'str',
            'avatar': 'str',
            'avatarmedium': 'str',
            'avatarfull': 'str',
            'profileurl': 'str',
            'personaname': 'str',
            'cheese': 'int',
            'fh_unavailable': 'bool',
            'loccountrycode': 'str',
            'rank_tier': 'int'
        }

        self.attribute_map = {
            'account_id': 'account_id',
            'score': 'score',
            'steamid': 'steamid',
            'avatar': 'avatar',
            'avatarmedium': 'avatarmedium',
            'avatarfull': 'avatarfull',
            'profileurl': 'profileurl',
            'personaname': 'personaname',
            'cheese': 'cheese',
            'fh_unavailable': 'fh_unavailable',
            'loccountrycode': 'loccountrycode',
            'rank_tier': 'rank_tier'
        }

        self._account_id = account_id
        self._score = score
        self._steamid = steamid
        self._avatar = avatar
        self._avatarmedium = avatarmedium
        self._avatarfull = avatarfull
        self._profileurl = profileurl
        self._personaname = personaname
        self._cheese = cheese
        self._fh_unavailable = fh_unavailable
        self._loccountrycode = loccountrycode
        self._rank_tier = rank_tier

    @property
    def account_id(self):
        """
        Gets the account_id of this InlineResponse20027Rankings.
        account_id

        :return: The account_id of this InlineResponse20027Rankings.
        :rtype: int
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """
        Sets the account_id of this InlineResponse20027Rankings.
        account_id

        :param account_id: The account_id of this InlineResponse20027Rankings.
        :type: int
        """

        self._account_id = account_id

    @property
    def score(self):
        """
        Gets the score of this InlineResponse20027Rankings.
        score

        :return: The score of this InlineResponse20027Rankings.
        :rtype: str
        """
        return self._score

    @score.setter
    def score(self, score):
        """
        Sets the score of this InlineResponse20027Rankings.
        score

        :param score: The score of this InlineResponse20027Rankings.
        :type: str
        """

        self._score = score

    @property
    def steamid(self):
        """
        Gets the steamid of this InlineResponse20027Rankings.
        steamid

        :return: The steamid of this InlineResponse20027Rankings.
        :rtype: str
        """
        return self._steamid

    @steamid.setter
    def steamid(self, steamid):
        """
        Sets the steamid of this InlineResponse20027Rankings.
        steamid

        :param steamid: The steamid of this InlineResponse20027Rankings.
        :type: str
        """

        self._steamid = steamid

    @property
    def avatar(self):
        """
        Gets the avatar of this InlineResponse20027Rankings.
        avatar

        :return: The avatar of this InlineResponse20027Rankings.
        :rtype: str
        """
        return self._avatar

    @avatar.setter
    def avatar(self, avatar):
        """
        Sets the avatar of this InlineResponse20027Rankings.
        avatar

        :param avatar: The avatar of this InlineResponse20027Rankings.
        :type: str
        """

        self._avatar = avatar

    @property
    def avatarmedium(self):
        """
        Gets the avatarmedium of this InlineResponse20027Rankings.
        avatarmedium

        :return: The avatarmedium of this InlineResponse20027Rankings.
        :rtype: str
        """
        return self._avatarmedium

    @avatarmedium.setter
    def avatarmedium(self, avatarmedium):
        """
        Sets the avatarmedium of this InlineResponse20027Rankings.
        avatarmedium

        :param avatarmedium: The avatarmedium of this InlineResponse20027Rankings.
        :type: str
        """

        self._avatarmedium = avatarmedium

    @property
    def avatarfull(self):
        """
        Gets the avatarfull of this InlineResponse20027Rankings.
        avatarfull

        :return: The avatarfull of this InlineResponse20027Rankings.
        :rtype: str
        """
        return self._avatarfull

    @avatarfull.setter
    def avatarfull(self, avatarfull):
        """
        Sets the avatarfull of this InlineResponse20027Rankings.
        avatarfull

        :param avatarfull: The avatarfull of this InlineResponse20027Rankings.
        :type: str
        """

        self._avatarfull = avatarfull

    @property
    def profileurl(self):
        """
        Gets the profileurl of this InlineResponse20027Rankings.
        profileurl

        :return: The profileurl of this InlineResponse20027Rankings.
        :rtype: str
        """
        return self._profileurl

    @profileurl.setter
    def profileurl(self, profileurl):
        """
        Sets the profileurl of this InlineResponse20027Rankings.
        profileurl

        :param profileurl: The profileurl of this InlineResponse20027Rankings.
        :type: str
        """

        self._profileurl = profileurl

    @property
    def personaname(self):
        """
        Gets the personaname of this InlineResponse20027Rankings.
        personaname

        :return: The personaname of this InlineResponse20027Rankings.
        :rtype: str
        """
        return self._personaname

    @personaname.setter
    def personaname(self, personaname):
        """
        Sets the personaname of this InlineResponse20027Rankings.
        personaname

        :param personaname: The personaname of this InlineResponse20027Rankings.
        :type: str
        """

        self._personaname = personaname

    @property
    def cheese(self):
        """
        Gets the cheese of this InlineResponse20027Rankings.
        cheese

        :return: The cheese of this InlineResponse20027Rankings.
        :rtype: int
        """
        return self._cheese

    @cheese.setter
    def cheese(self, cheese):
        """
        Sets the cheese of this InlineResponse20027Rankings.
        cheese

        :param cheese: The cheese of this InlineResponse20027Rankings.
        :type: int
        """

        self._cheese = cheese

    @property
    def fh_unavailable(self):
        """
        Gets the fh_unavailable of this InlineResponse20027Rankings.
        fh_unavailable

        :return: The fh_unavailable of this InlineResponse20027Rankings.
        :rtype: bool
        """
        return self._fh_unavailable

    @fh_unavailable.setter
    def fh_unavailable(self, fh_unavailable):
        """
        Sets the fh_unavailable of this InlineResponse20027Rankings.
        fh_unavailable

        :param fh_unavailable: The fh_unavailable of this InlineResponse20027Rankings.
        :type: bool
        """

        self._fh_unavailable = fh_unavailable

    @property
    def loccountrycode(self):
        """
        Gets the loccountrycode of this InlineResponse20027Rankings.
        loccountrycode

        :return: The loccountrycode of this InlineResponse20027Rankings.
        :rtype: str
        """
        return self._loccountrycode

    @loccountrycode.setter
    def loccountrycode(self, loccountrycode):
        """
        Sets the loccountrycode of this InlineResponse20027Rankings.
        loccountrycode

        :param loccountrycode: The loccountrycode of this InlineResponse20027Rankings.
        :type: str
        """

        self._loccountrycode = loccountrycode

    @property
    def rank_tier(self):
        """
        Gets the rank_tier of this InlineResponse20027Rankings.
        rank_tier

        :return: The rank_tier of this InlineResponse20027Rankings.
        :rtype: int
        """
        return self._rank_tier

    @rank_tier.setter
    def rank_tier(self, rank_tier):
        """
        Sets the rank_tier of this InlineResponse20027Rankings.
        rank_tier

        :param rank_tier: The rank_tier of this InlineResponse20027Rankings.
        :type: int
        """

        self._rank_tier = rank_tier

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
